### ISSUE TITLE
ActionCreators and a typo

### ISSUE THREAD

**Issue by zhoul-HS** [izumin5210/Droidux#37]
```java
class FetchTodoListAction implements AsyncAction {
    private final TodoListApi client;

 // wrong constructor
    public ReceiveTodoListAction(TodoListApi client) {
        this.client = client;
    }

......
```

1. too lazy to do a PR for this but it's the wrong constructor =)
2. you are missing an important part of async actions that are provided to you by action creators, which you do not have. Action creators allow you to dispatch actions! but we can use it in the call method instead
```java
class DoingFetchAction implements Action {}

class FetchTodoListAction implements AsyncAction {
    private final TodoListApi client;

    public FetchTodoListAction (TodoListApi client) {
        this.client = client;
    }

 Observable<ReceiveTodoListAction> call(Dispatcher dispatcher) {
        dispatcher.dispatch(new DoingFetchAction()); // notify you are starting a fetch
        return client.fetch()
                .map(todoList -> {
                    this.todoList = todoList;
                    return new ReceiveTodoListAction(todoList);
                });
    }
}
```
something like that
see http://rackt.org/redux/docs/advanced/AsyncActions.html

just a thought. the important part is that async actions receive a dispatch function or dispatcher so they can do dispatch themselves.

**Comment by izumin5210** [comment]
@zhoul-HS 
Thank you for reporting your issue !

> too lazy to do a PR for this but it's the wrong constructor =)

i will fix it as soon as possible.

> you are missing an important part of async actions that are provided to you by action creators, which you do not have. Action creators allow you to dispatch actions! but we can use it in the call method instead

you are right. Droidux v0.6.0 will support this feature!

```java
public interface AsyncAction<T> extends Action<T> {
    // before
    // Observable<Action> call();

    // after
    Observable<Action> call(Dispatcher dispatcher);
}
```

**Comment by izumin5210** [comment]
close via #38 and #39
